- update workflow to only try and push changes if there are changes to push

diff --git a/.github/workflows/build-graphiql.yml b/.github/workflows/build-graphiql.yml
--- a/.github/workflows/build-graphiql.yml
+++ b/.github/workflows/build-graphiql.yml
@@ -42,5 +42,15 @@ jobs:
         id: commit-changes
         run: |
           git add --force build
-          git commit -m "Apply GraphiQL build changes"
-          git push
+          set +e  # Grep succeeds with nonzero exit codes to show results.
+          git status | grep modified
+          if [ $? -eq 0 ]
+          then
+            set -e
+            git commit -m "Apply GraphiQL build changes"
+            git push
+          else
+            set -e
+            echo "No changes since last run"
+          fi
+          
