- update workflow to auto-commit phpcbf fixed files then run phpcs to output any other errors

diff --git a/.github/workflows/wordpress-coding-standards.yml b/.github/workflows/wordpress-coding-standards.yml
--- a/.github/workflows/wordpress-coding-standards.yml
+++ b/.github/workflows/wordpress-coding-standards.yml
@@ -1,44 +1,59 @@
 name: WordPress Coding Standards
 
-on:
-  push:
-    branches:
-      - develop
-      - master
-  pull_request:
-    branches:
-      - develop
-      - master
+on: pull_request_target
 
 jobs:
-  run:
+  phpcbf-fix:
     runs-on: ubuntu-latest
-    name: PHPCS
-    strategy:
-      matrix:
-        php: [ 8.1 ]
-
     steps:
       - name: Cancel previous runs of this workflow (pull requests only)
         if: ${{ github.event_name == 'pull_request' }}
         uses: styfle/cancel-workflow-action@0.11.0
         with:
           access_token: ${{ github.token }}
-
-      - name: Checkout
+          
+      - name: Checkout code
         uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: 0
 
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
-          php-version: ${{ matrix.php }}
+          php-version: '8.0'
           tools: composer:v2
-          coverage: none
-      
-      - name: Install dependencies
-        uses: ramsey/composer-install@v2
+
+      - name: Install Dependencies
+        run: composer install --prefer-dist --no-progress --no-suggest
+
+      - name: Get Changed Files
+        id: get-changed-files
+        uses: lots0logs/gh-action-get-changed-files@v2.1.4
+
+      - name: Run PHPCBF on Changed Files and Check for Errors
+        id: phpcbf
+        run: |
+          FILES_CHANGED="${{ steps.get-changed-files.outputs.all }}"
+          if [ -n "$FILES_CHANGED" ]; then
+            PHPCBF_OUTPUT=$(./vendor/bin/phpcbf $FILES_CHANGED || true)
+            echo "PHPCBF_OUTPUT<<EOF" >> $GITHUB_ENV
+            echo "$PHPCBF_OUTPUT" >> $GITHUB_ENV
+            echo "EOF" >> $GITHUB_ENV
+            echo "::set-output name=phpcbf-output::$PHPCBF_OUTPUT"
+            if echo "$PHPCBF_OUTPUT" | grep -q "ERROR"; then
+              echo "Unfixable PHPCBF errors detected"
+              exit 1
+            fi
+          fi
+
+      - name: Commit changes
+        if: ${{ success() }}
+        uses: stefanzweifel/git-auto-commit-action@v4.13.0
         with:
-          composer-options: "--no-progress"
+          commit_message: 'Apply PHPCBF fixes'
+          branch: ${{ github.head_ref }}
+          file_pattern: $FILES_CHANGED
 
       - name: Run PHPCS
         run: composer run-script check-cs
